name: Build gpicview Portable Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install musl tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            musl-tools build-essential git curl zip \
            libgtk2.0-dev libimlib2-dev \
            libjpeg-turbo8-dev libjpeg8-dev libturbojpeg \
            libpng-dev libpng16-16 \
            libatspi2.0-dev libatspi2.0-0 \
            libfontconfig1-dev libfontconfig1 \
            intltool pkg-config

      - name: Clone and build gpicview with musl
        run: |
          git clone https://github.com/lxde/gpicview.git
          cd gpicview
          ./autogen.sh
          CC="musl-gcc" CFLAGS="-I/usr/include" LDFLAGS="-L/usr/lib/x86_64-linux-gnu -ljpeg" ./configure --prefix=/usr --enable-static --disable-shared
          make LDFLAGS="-static -L/usr/lib/x86_64-linux-gnu -ljpeg" || { echo "Build failed"; exit 1; }
          strip src/gpicview

      - name: Prepare staging directory
        run: |
          mkdir -p ~/gpicview-install/usr/bin
          mkdir -p ~/gpicview-install/etc/fonts
          cp gpicview/src/gpicview ~/gpicview-install/usr/bin/gpicview-bin
          cp -r /etc/fonts/fonts.conf ~/gpicview-install/etc/fonts/

      - name: Create launcher script
        run: |
          cd ~/gpicview-install/usr/bin
          cat > gpicview << EOF
          #!/bin/bash
          DIR="\$(dirname "\$(realpath "\$0")")"
          export FONTCONFIG_PATH="\$DIR/../etc/fonts"
          "\$DIR/gpicview-bin" "\$@"
          EOF
          chmod +x gpicview
          cat gpicview

      - name: Create zip file
        run: |
          cd ~/gpicview-install
          zip -r ~/gpicview-portable.zip .

      - name: Generate SHA256 checksum
        run: |
          sha256sum ~/gpicview-portable.zip > ~/gpicview-portable.zip.sha256
          cat ~/gpicview-portable.zip.sha256

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpicview-portable
          path: |
            ~/gpicview-portable.zip
            ~/gpicview-portable.zip.sha256
