name: Build st Portable

on:
  push:
    branches:
      - main  # or replace with your default branch
    paths:
      - ".github/workflows/st-main.yml"
      - "st/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential curl git wget make \
            libx11-dev libxft-dev libxext-dev pkg-config \
            patchelf zip

      - name: Download and extract st
        run: |
          mkdir -p ~/st-build
          cd ~/st-build
          wget https://dl.suckless.org/st/st-0.9.tar.gz
          tar -xzf st-0.9.tar.gz

      - name: Inject config.h (clean, compatible version)
        run: |
          cat > ~/st-build/st-0.9/config.h << 'EOF'
          #include <X11/keysym.h>

          static char *font = "monospace:pixelsize=14:antialias=true:autohint=true";
          static int borderpx = 2;
          static char *shell = "/bin/sh";
          static float cwscale = 1.0;
          static float chscale = 1.0;
          static unsigned int cursorshape = 2;
          static int cursorblink = 0;
          static unsigned int cursorthickness = 2;
          static int bellvolume = 0;
          static unsigned int defaultfg = 7;
          static unsigned int defaultbg = 0;
          static unsigned int defaultcs = 7;

          static const char *colorname[] = {
            "black", "red", "green", "yellow",
            "blue", "magenta", "cyan", "white",
          };

          static unsigned int tabspaces = 8;

          static const char ascii_printable[] =
            " !\"#$%&'()*+,-./0123456789:;<=>?"
            "@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_"
            "`abcdefghijklmnopqrstuvwxyz{|}~";
          EOF

      - name: Build st
        run: |
          cd ~/st-build/st-0.9
          make clean
          make

      - name: Bundle binary
        run: |
          cd ~/st-build/st-0.9
          mkdir -p out
          cp st out/
          patchelf --set-rpath '$ORIGIN' out/st || true
          zip -j st-portable.zip out/st

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: st-portable
          path: ~/st-build/st-0.9/st-portable.zip
