name: Build ST Terminal (Static Portable)

on:
  push:
    paths:
      - ".github/workflows/st.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential curl git wget make \
            libx11-dev libxft-dev libxext-dev pkg-config \
            libfontconfig-dev libfreetype-dev libpng-dev \
            patchelf zip

      - name: Download and extract st
        run: |
          mkdir -p ~/st-build
          cd ~/st-build
          wget https://dl.suckless.org/st/st-0.9.tar.gz
          tar -xzf st-0.9.tar.gz

      - name: Copy and patch config.h
        run: |
          cd ~/st-build/st-0.9
          cp config.def.h config.h

          # Customize font, shell, border, etc.
          sed -i 's|^\(static char \*font = \).*|\1"monospace:pixelsize=14:antialias=true:autohint=true";|' config.h
          sed -i 's|^\(static int borderpx = \).*|\12;|' config.h
          sed -i 's|^\(static char \*shell = \).*|\1"/bin/sh";|' config.h
          sed -i 's|^\(static int cursorblink = \).*|\10;|' config.h
          sed -i 's|^\(static unsigned int cursorshape = \).*|\12;|' config.h

          # Replace full colorname[] block with one that includes cursor color
          sed -i '/^static char \*colorname\[\] = {/,/^};/c\static char *colorname[] = {\n  "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",\n  [256] = "#cccccc", /* foreground */\n  [257] = "#000000", /* background */\n  [258] = "#00ff00", /* cursor (green) */\n};' config.h

          # Set default foreground/background/cursor colors
          sed -i 's|^\(unsigned int defaultfg = \).*|\1256;|' config.h
          sed -i 's|^\(unsigned int defaultbg = \).*|\1257;|' config.h
          sed -i 's|^\(unsigned int defaultcs = \).*|\1258;|' config.h
          sed -i 's|^\(unsigned int defaultrcs = \).*|\1258;|' config.h

      - name: Build ST
        run: |
          cd ~/st-build/st-0.9
          make

      - name: Make portable binary directory
        run: |
          mkdir -p ~/st-build/out/usr/bin
          cp ~/st-build/st-0.9/st ~/st-build/out/usr/bin/

      - name: Patch binary with patchelf
        run: |
          patchelf --set-rpath '$ORIGIN/../lib' ~/st-build/out/usr/bin/st || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: st-portable
          path: ~/st-build/out
