name: Build ST Terminal (portable)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Portable ST Binary
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential wget curl git make \
            libx11-dev libxft-dev libxext-dev pkg-config \
            libfontconfig-dev libfreetype-dev \
            patchelf zip

      - name: Download st source
        run: |
          mkdir -p ~/st-build
          cd ~/st-build
          wget https://dl.suckless.org/st/st-0.9.tar.gz
          tar -xzf st-0.9.tar.gz

      - name: Copy and patch config.h
        run: |
          cd ~/st-build/st-0.9
          cp config.def.h config.h

          # Apply your customizations
          sed -i 's|^\(static char \*font = \).*|\1"monospace:pixelsize=14:antialias=true:autohint=true";|' config.h
          sed -i 's|^\(static int borderpx = \).*|\12;|' config.h
          sed -i 's|^\(static char \*shell = \).*|\1"/bin/sh";|' config.h
          sed -i 's|^\(static int cursorblink = \).*|\10;|' config.h
          sed -i 's|^\(static unsigned int cursorshape = \).*|\12;|' config.h

      - name: Build st
        run: |
          cd ~/st-build/st-0.9
          make

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: st-x86_64
          path: ~/st-build/st-0.9/st
