name: Build st

on:
  push:
    paths:
      - '.github/workflows/st.yml'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential curl git wget make \
            libx11-dev libxft-dev libxext-dev pkg-config

      - name: Download and extract st
        run: |
          mkdir -p ~/st-build
          cd ~/st-build
          wget https://dl.suckless.org/st/st-0.9.tar.gz
          tar -xzf st-0.9.tar.gz

      - name: Patch config.h
        run: |
          cat > ~/st-build/st-0.9/config.h << 'EOF'
          static char *font = "monospace:pixelsize=14:antialias=true:autohint=true";
          static int borderpx = 2;
          static char *shell = "/bin/sh";

          static float cwscale = 1.0;
          static float chscale = 1.0;

          static unsigned int cursorshape = 2; // 2 = block
          static int cursorblink = 0;

          static char *colorname[] = {
            [0] = "black",
            [1] = "red",
            [2] = "green",
            [3] = "yellow",
            [4] = "blue",
            [5] = "magenta",
            [6] = "cyan",
            [7] = "white",
            [8] = "#00ff00",
            [256] = "cyan",
            [257] = "black",
            [258] = "#00ff00"
          };

          unsigned int defaultfg = 256;
          unsigned int defaultbg = 257;
          unsigned int defaultcs = 258;
          unsigned int defaultrcs = 258;

          static unsigned int tabspaces = 8;
          wchar_t *worddelimiters = L" ";
          EOF

      - name: Build st
        run: |
          cd ~/st-build/st-0.9
          make

      - name: Upload st binary
        uses: actions/upload-artifact@v4
        with:
          name: st
          path: ~/st-build/st-0.9/st
