name: Build st Portable

on:
  push:
    branches:
      - main  # <- CHANGE THIS IF YOUR DEFAULT BRANCH IS NOT "main"
    paths:
      - '.github/workflows/st.yml'
      - 'st/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential curl git wget make \
            libx11-dev libxft-dev libxext-dev pkg-config \
            patchelf zip

      - name: Download and extract st
        run: |
          mkdir -p ~/st-build
          cd ~/st-build
          wget https://dl.suckless.org/st/st-0.9.tar.gz
          tar -xzf st-0.9.tar.gz

      - name: Inject config.h
        run: |
          cp .github/workflows/config.h ~/st-build/st-0.9/config.h

      - name: Patch x.c for cursor color
        run: |
          cd ~/st-build/st-0.9
          sed -i '/xdrawcursor/,/^}/s/drawcol = .*/drawcol = dc.col[defaultcs];/' x.c

      - name: Build st
        run: |
          cd ~/st-build/st-0.9
          make

      - name: Bundle binary
        run: |
          cd ~/st-build/st-0.9
          mkdir -p out
          cp st out/
          patchelf --set-rpath '$ORIGIN' out/st || true
          zip -j st-portable.zip out/st

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: st-portable
          path: ~/st-build/st-0.9/st-portable.zip
