name: Build st portable binary

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential curl git wget make \
            libx11-dev libxft-dev libxext-dev pkg-config \
            patchelf zip

      - name: Download and extract st source
        run: |
          mkdir -p ~/st-build
          cd ~/st-build
          wget https://dl.suckless.org/st/st-0.9.tar.gz
          tar -xzf st-0.9.tar.gz

      - name: Patch config.h
        run: |
          cat > ~/st-build/st-0.9/config.h << 'EOF'
          static char *font = "monospace:pixelsize=14:antialias=true:autohint=true";
          static int borderpx = 2;
          static char *shell = "/bin/sh";

          static float cwscale = 1.0;
          static float chscale = 1.0;

          static unsigned int cursorshape = 2; // block
          static int cursorblink = 0;

          static char *colorname[] = {
            [0] = "black",
            [1] = "red",
            [2] = "green",
            [3] = "yellow",
            [4] = "blue",
            [5] = "magenta",
            [6] = "cyan",
            [7] = "white",
            [256] = "cyan",    // foreground
            [257] = "black",   // background
            [258] = "#00ff00"  // cursor color
          };

          unsigned int defaultfg = 256;
          unsigned int defaultbg = 257;
          unsigned int defaultcs = 258;
          unsigned int defaultrcs = 258;

          unsigned int tabspaces = 8;
          wchar_t *worddelimiters = L" ";
          EOF

      - name: Patch x.c to fix cursor drawing
        run: |
          cd ~/st-build/st-0.9
          sed -i '/xdrawcursor/,/^}/s/drawcol = .*/drawcol = dc.col[defaultcs];/' x.c

      - name: Build st
        run: |
          cd ~/st-build/st-0.9
          make

      - name: Strip and prepare portable binary
        run: |
          cd ~/st-build/st-0.9
          strip st
          mkdir -p ~/st-out
          cp st ~/st-out/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: st-portable
          path: ~/st-out/st
