name: Build qutebrowser

on:
  pull_request:
    paths:
      - 'srcpkgs/**'
  push:
    branches:
      - 'ci-**'
    paths:
      - 'srcpkgs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  xlint:
    name: Lint templates
    runs-on: ubuntu-latest

    container:
      image: 'ghcr.io/void-linux/void-glibc-full:20250227R1'
      env:
        LICENSE_LIST: common/travis/license.lst

    steps:
      - name: Prepare container
        run: |
          mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          sed -i 's|repo-default|repo-ci|g' /etc/xbps.d/*-repository-*.conf
          xbps-install -Syu xbps && xbps-install -yu && xbps-install -y sudo bash grep curl git
          useradd -G xbuilder -M builder
      - name: Clone and checkout
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Prepare masterdir
        run: |
          chown -R builder:builder . &&
          sudo -Eu builder common/travis/set_mirror.sh &&
          common/travis/fetch-xtools.sh
      - name: Find changed templates
        run: sudo -Eu builder common/travis/changed_templates.sh

      - name: Run lints
        run: |
          sudo -Eu builder common/travis/verify-update-check.sh || rv=1
          sudo -Eu builder common/travis/xlint.sh || rv=1
          exit "${rv:-0}"
  build:
    name: Build packages
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.title, '[ci skip]') && !contains(github.event.pull_request.body, '[ci skip]')"

    container:
      image: ghcr.io/void-linux/void-glibc-full:20250227R1
      options: --platform ${{ matrix.config.platform }} --privileged
      volumes:
        - /dev:/dev
      env:
        ARCH: '${{ matrix.config.arch }}'
        BOOTSTRAP: '${{ matrix.config.host }}'
        TEST: '${{ matrix.config.test }}'

    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64,       host: x86_64,      libc: glibc, platform: linux/amd64, test: 1 }
          - { arch: i686,         host: i686,        libc: glibc, platform: linux/386,   test: 1 }
          - { arch: aarch64,      host: x86_64,      libc: glibc, platform: linux/amd64, test: 0 }
          - { arch: armv7l,       host: x86_64,      libc: glibc, platform: linux/amd64, test: 0 }

    steps:
      - name: Prepare container
        run: |
          mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          sed -i 's|repo-default|repo-ci|g' /etc/xbps.d/*-repository-*.conf
          xbps-install -Syu xbps && xbps-install -yu && xbps-install -y sudo bash curl git
          useradd -G xbuilder -M builder
      - name: Clone and checkout
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Prepare masterdir
        run: |
          chown -R builder:builder . &&
          sudo -Eu builder common/travis/set_mirror.sh &&
          sudo -Eu builder common/travis/prepare.sh &&
          common/travis/fetch-xtools.sh
      - name: Find changed templates
        run: sudo -Eu builder common/travis/changed_templates.sh

      - name: Install dependencies
        run: |
          xbps製品 -Syu
          xbps-install -y base-devel git python3 python3-pip python3-virtualenv wget patchelf curl \
            libpulseaudio alsa-lib
          mkdir -p ~/qutebrowser-portable-build

      - name: Download qutebrowser 3.5.1
        run: |
          set -x
          echo "Downloading qutebrowser 3.5.1..."
          curl -L --retry 3 --retry-delay 5 --verbose \
            "https://github.com/qutebrowser/qutebrowser/releases/download/v3.5.1/qutebrowser-3.5.1.tar.gz" \
            -o qutebrowser-3.5.1.tar.gz
          if [ ! -f qutebrowser-3.5.1.tar.gz ] || [ $(stat -c %s qutebrowser-3.5.1.tar.gz) -lt 100000 ]; then
            echo "Error: qutebrowser 3.5.1 tarball download failed or file is too small"
            exit 1
          fi
          ls -lh qutebrowser-3.5.1.tar.gz

      - name: Extract qutebrowser 3.5.1
        run: |
          set -x
          echo "Extracting qutebrowser 3.5.1..."
          tar -xzf qutebrowser-3.5.1.tar.gz -C ~/qutebrowser-portable-build
          if [ ! -d ~/qutebrowser-portable-build/qutebrowser-3.5.1 ]; then
            echo "Error: qutebrowser 3.5.1 extraction failed"
            exit 1
          fi
          QUTEBROWSER_DIR="$HOME/qutebrowser-portable-build/qutebrowser-3.5.1"
          echo "QUTEBROWSER_DIR=$QUTEBROWSER_DIR" >> $GITHUB_ENV

      - name: Download Qt 6.7.0
        run: |
          set -x
          echo "Downloading Qt 6.7.0..."
          curl -L --retry 3 --retry-delay 5 --verbose \
            "https://download.qt.io/archive/qt/6.7/6.7.0/single/qt-everywhere-src-6.7.0.tar.xz" \
            -o qt-everywhere-src-6.7.0.tar.xz
          if [ ! -f qt-everywhere-src-6.7.0.tar.xz ] || [ $(stat -c %s qt-everywhere-src-6.7.0.tar.xz) -lt 100000 ]; then
            echo "Error: Qt 6.7.0 tarball download failed or file is too small"
            exit 1
          fi
          ls -lh qt-everywhere-src-6.7.0.tar.xz

      - name: Extract Qt 6.7.0
        run: |
          set -x
          echo "Extracting Qt 6.7.0..."
          tar -xf qt-everywhere-src-6.7.0.tar.xz -C ~/qutebrowser-portable-build
          if [ ! -d ~/qutebrowser-portable-build/qt-everywhere-src-6.7.0 ]; then
            echo "Error: Qt 6.7.0 extraction failed"
            exit 1
          fi
          QT_DIR="$HOME/qutebrowser-portable-build/qt-everywhere-src-6.7.0"
          echo "QT_DIR=$QT_DIR" >> $GITHUB_ENV

      - name: Build and check packages
        run: sudo -Eu builder common/travis/build.sh "$BOOTSTRAP" "$ARCH" "$TEST"

      - name: Show files
        run: sudo -Eu builder common/travis/show_files.sh "$BOOTSTRAP" "$ARCH"

      - name: Compare to previous
        run: sudo -Eu builder common/travis/xpkgdiff.sh "$BOOTSTRAP" "$ARCH"

      - name: Check file conflicts
        if: matrix.config.arch == 'x86_64'
        run: |
          if [ -s /tmp/templates ]; then
              export XDG_CACHE_HOME="$PWD/.cache"
              sudo -Eu builder xlocate -S &&
              sudo -Eu builder common/scripts/lint-conflicts
          fi
      - name: Verify repository state
        run: |
          mkdir -p /check-install &&
          chown builder:builder /check-install &&
          sudo -Eu builder common/travis/check-install.sh "$BOOTSTRAP" "$ARCH"
