name: Build Surf Browser

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Add Jammy repository and install dependencies
        run: |
          sudo apt-get update
          # Add Ubuntu 22.04 (Jammy) repository
          echo "deb http://archive.ubuntu.com/ubuntu jammy main universe" | sudo tee /etc/apt/sources.list.d/jammy.list
          sudo apt-get update
          sudo apt-get install -y \
            git \
            build-essential \
            libwebkit2gtk-4.0-dev \
            libgtk-3-dev \
            libgcr-3-dev \
            pkg-config \
            curl

      - name: Clone Surf repository
        run: |
          git clone https://git.suckless.org/surf
          cd surf
          git checkout master

      - name: Build Surf
        run: |
          cd surf
          make
          make clean objects

      - name: Prepare portable binary
        run: |
          mkdir -p surf-portable
          cp surf/surf surf-portable/
          chmod +x surf-portable/surf
          ldd surf/surf | grep "=>" | awk '{print $3}' | xargs -I {} cp {} surf-portable/

      - name: Upload Surf binary
        uses: actions/upload-artifact@v4
        with:
          name: surf-portable-binary
          path: surf-portable/
          retention-days: 7
