name: Build Surf Browser

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            build-essential \
            libwebkit2gtk-4.0-dev \
            libgtk-3-dev \
            libgcr-3-dev \
            pkg-config \
            curl

      - name: Clone Surf repository
        run: |
          git clone https://git.suckless.org/surf
          cd surf

      - name: Build Surf
        run: |
          cd surf
          make  # Builds surf and webext-surf.so
          # Do not run 'make clean' here to preserve binaries

      - name: Prepare portable binary
        run: |
          mkdir -p surf-portable
          cp surf/surf surf-portable/
          cp surf/webext-surf.so surf-portable/  # Include the web extension
          chmod +x surf-portable/surf
          ldd surf/surf | grep "=>" | awk '{print $3}' | xargs -I {} cp {} surf-portable/
          ldd surf/webext-surf.so | grep "=>" | awk '{print $3}' | xargs -I {} cp {} surf-portable/

      - name: Upload Surf binary
        uses: actions/upload-artifact@v4
        with:
          name: surf-portable-binary
          path: surf-portable/
          retention-days: 7
