name: Build Surf Browser

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            build-essential \
            libwebkit2gtk-4.0-dev \
            libgtk-3-dev \
            libgcr-3-dev \
            pkg-config \
            curl

      - name: Clone Surf repository
        run: |
          git clone https://git.suckless.org/surf
          ls -la
          cd surf || { echo "Failed to cd into surf"; exit 1; }
          pwd
          ls -la

      - name: Build Surf
        run: |
          cd surf || { echo "Failed to cd into surf"; exit 1; }
          make || { echo "Make failed"; exit 1; }
          ls -l surf webext-surf.so || { echo "Binaries not found"; exit 1; }

      - name: Prepare portable binary
        run: |
          mkdir -p surf-portable || { echo "Failed to create surf-portable"; exit 1; }
          cp surf/surf surf-portable/ || { echo "Failed to copy surf"; exit 1; }
          cp surf/webext-surf.so surf-portable/ || { echo "Failed to copy webext-surf.so"; exit 1; }
          chmod +x surf-portable/surf
          ldd surf/surf | grep "=>" | awk '{print $3}' | xargs -I {} cp {} surf-portable/ || { echo "Failed to copy surf dependencies"; exit 1; }
          ldd surf/webext-surf.so | grep "=>" | awk '{print $3}' | xargs -I {} cp {} surf-portable/ || { echo "Failed to copy webext-surf.so dependencies"; exit 1; }
          ls -la surf-portable/ || { echo "Failed to list surf-portable contents"; exit 1; }
          du -sh surf-portable/  # Show size of portable directory

      - name: Upload Surf binary
        uses: actions/upload-artifact@v4
        with:
          name: surf-portable-binary
          path: surf-portable/
          retention-days: 7
